//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVC_HomeMaticNotification.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConfigTemplate.xml")]
        public string NotifierConfigFile {
            get {
                return ((string)(this["NotifierConfigFile"]));
            }
            set {
                this["NotifierConfigFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://homematicCCU2.halnet.selfip.org")]
        public string HmcUrl {
            get {
                return ((string)(this["HmcUrl"]));
            }
            set {
                this["HmcUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string NotifierReconnectTimerSec {
            get {
                return ((string)(this["NotifierReconnectTimerSec"]));
            }
            set {
                this["NotifierReconnectTimerSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServiceEventSource {
            get {
                return ((string)(this["ServiceEventSource"]));
            }
            set {
                this["ServiceEventSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string NotifierQueryTimerSec {
            get {
                return ((string)(this["NotifierQueryTimerSec"]));
            }
            set {
                this["NotifierQueryTimerSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string NotifierQueryFullRequestSec {
            get {
                return ((string)(this["NotifierQueryFullRequestSec"]));
            }
            set {
                this["NotifierQueryFullRequestSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string NotificationSmtpHost {
            get {
                return ((string)(this["NotificationSmtpHost"]));
            }
            set {
                this["NotificationSmtpHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public string NotificationSmtpPort {
            get {
                return ((string)(this["NotificationSmtpPort"]));
            }
            set {
                this["NotificationSmtpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user@gmail.com")]
        public string NotificationSmtpCredUser {
            get {
                return ((string)(this["NotificationSmtpCredUser"]));
            }
            set {
                this["NotificationSmtpCredUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sprScrPsswrd!")]
        public string NotificationSmtpCredPw {
            get {
                return ((string)(this["NotificationSmtpCredPw"]));
            }
            set {
                this["NotificationSmtpCredPw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user@gmail.com")]
        public string NotificationSmtpMailFrom {
            get {
                return ((string)(this["NotificationSmtpMailFrom"]));
            }
            set {
                this["NotificationSmtpMailFrom"] = value;
            }
        }
    }
}
