using System;

namespace TRoschinsky.Service.HomeMaticNotification
{
    /// <summary>
    /// Just an exception class for errors generated by HomeMaticNotification. 
    /// There's nothing special about it.
    /// </summary>
    public class HMNException : Exception
    {
        public HMNException(string notifierMessage, Exception notifierInnerException)
            : base(notifierMessage, notifierInnerException)
        {

        }
        public HMNException(string notifierMessage)
            : base(notifierMessage)
        {

        }
    }
}
